/*
bluepp
2016-08-29
May the force be with me!

https://leetcode.com/problems/find-the-difference/

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/

    char findTheDifference(string s, string t) {
        
        unordered_map<char, int> map;
        
        for (auto p : s)
        {
            map[p]++;
        }
        
        for (auto p : t)
        {
            if (--map[p] < 0)
            {
                return p;
            }
           
        }
        
        return 0;
        
    }
    
  
  /* XOR */  
  char findTheDifference(string s, string t) {
        
        int ret = 0;
        
        for (auto p : s)
        {
            ret ^= p;
        }
        
        for (auto p : t)
        {
            ret ^= p;
        }
        
        return ret;
    }
